# Generated by Django 3.2.4 on 2021-08-17 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20210816_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name_plural': 'Category ...for... shopping'},
        ),
        migrations.CreateModel(
            name='OnlineBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Booker`s name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.IntegerField(default=0, verbose_name='How many ticket')),
                ('children', models.IntegerField(default=0, verbose_name='How many children')),
                ('description', models.TextField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exhibition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exhibition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
