# Generated by Django 3.2.4 on 2021-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210817_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinebooking',
            options={'verbose_name_plural': 'Online Bookings'},
        ),
        migrations.AlterField(
            model_name='onlinebooking',
            name='description',
            field=models.TextField(),
        ),
    ]
