# Generated by Django 3.2.4 on 2021-08-18 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210817_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=60, verbose_name='Organizer Name')),
                ('description', models.TextField(default='Can you describe your Museum?')),
                ('image', models.ImageField(upload_to='Event', verbose_name='Image to Event')),
                ('cost_adults', models.IntegerField(default=0)),
                ('cost_children', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(null=True, verbose_name='Start-Time')),
                ('end_time', models.TimeField(null=True, verbose_name='End-Time')),
            ],
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='Event/gallery/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='main.event')),
            ],
        ),
    ]
