# Generated by Django 3.2.4 on 2021-08-18 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_eventgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinebooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.event'),
        ),
    ]
